apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-new
  name: dotnet-new
  namespace: profile
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dotnet-new
  template:
    metadata:
      labels:
        app: dotnet-new
    spec:
      containers:
        - env:
            - name: PYROSCOPE_APPLICATION_NAME
              value: dotnet-new_new_app
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://logtail-kubernetes-metrics.sls-monitoring:4040"
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-dotnet-new'
          imagePullPolicy: Always
          name: dotnet-new
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

