apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: profile
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - env:
            - name: PYROSCOPE_APP_NAME
              value: nodejs_app
            - name: PYROSCOPE_SERVER
              value: "http://logtail-kubernetes-metrics.sls-monitoring:4040"
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-nodejs'
          imagePullPolicy: Always
          name: nodejs
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
        - env:
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-nodejs-generator'
          imagePullPolicy: Always
          name: generator
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

