apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rust
  name: rust
  namespace: profile
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rust
  template:
    metadata:
      labels:
        app: rust
    spec:
      containers:
        - env:
            - name: PYROSCOPE_APPLICATION_NAME
              value: golang_rust_app
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://logtail-kubernetes-metrics.sls-monitoring:5050"
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-rust'
          imagePullPolicy: Always
          name: rust
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
        - env:
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-rust-generator'
          imagePullPolicy: Always
          name: generator
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

