apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java
  name: java
  namespace: profile
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - env:
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-java'
          imagePullPolicy: Always
          name: javaagent
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
