apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java
  name: javaagent
  namespace: profile
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: javaagent
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - env:
            - name: PYROSCOPE_APPLICATION_NAME
              value: javaagent-demo
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://logtail-kubernetes-metrics.sls-monitoring:4040"
            - name: PYROSCOPE_FORMAT
              value: jfr
            - name: PYROSCOPE_PROFILER_EVENT
              value: wall
            - name: PYROSCOPE_PROFILER_ALLOC
              value: 2m
            - name: PYROSCOPE_PROFILER_LOCK
              value: 10ms
          image: 'registry-vpc.cn-beijing.aliyuncs.com/log-service/logtail:profile-javaagent'
          imagePullPolicy: Always
          name: javaagent
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
